version: 2
updates:
  - package-ecosystem: pip
    directory: /api
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      next-and-react:
        patterns: ["next", "react", "react-dom", "eslint-config-next"]
  - package-ecosystem: docker
    directories: ["/api", "/web"]
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
