/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The process is up */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The database answers and the catalog is loaded */
        get: operations["ready_api_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Choices and assumptions the web app shows */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Published programs (F11.2) */
        get: operations["programs_api_v1_programs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programs/{program_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A program's requirement tree */
        get: operations["program_detail_api_v1_programs__program_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programs/{program_id}/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gateway courses and the longest prerequisite chain (F3.2) */
        get: operations["insights_api_v1_programs__program_id__insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search the catalog */
        get: operations["courses_api_v1_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A course with its rules shown beside their source text (F0.2) */
        get: operations["course_detail_api_v1_courses__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Read a pasted SIS Course History page (F11.3) */
        post: operations["parse_history_api_v1_history_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/planner/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Progress per requirement and what is left (F1.2, F4) */
        post: operations["progress_api_v1_planner_progress_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/planner/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** A term-by-term plan to graduation (F1.3, F1.4, F1.6) */
        post: operations["plan_api_v1_planner_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/planner/what-if": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** What dropping or delaying a course does to graduation (F1.5) */
        post: operations["plan_what_if_api_v1_planner_what_if_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/planner/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ranked electives for each open requirement (F2.2) */
        post: operations["recommendations_api_v1_planner_recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rules to review, each beside its source sentence */
        get: operations["list_rules_api_v1_admin_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/rules/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check a rule written in the rule language without saving it */
        post: operations["check_rule_api_v1_admin_rules_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Correct a rule by hand (F0.3); the correction survives re-imports */
        put: operations["correct_rule_api_v1_admin_rules__rule_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/rules/{rule_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark the rule in force as checked */
        post: operations["approve_rule_api_v1_admin_rules__rule_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/rules/{rule_id}/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Drop a correction and go back to the parsed rule */
        delete: operations["remove_override_api_v1_admin_rules__rule_id__override_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Program imports, newest first */
        get: operations["imports_api_v1_admin_imports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin actions, newest first (F9.3) */
        get: operations["audit_api_v1_admin_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminRuleListOut */
        AdminRuleListOut: {
            /** Total */
            total: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Rules */
            rules: components["schemas"]["AdminRuleOut"][];
        };
        /** AdminRuleOut */
        AdminRuleOut: {
            /** Id */
            id: number;
            /** Course Code */
            course_code: string;
            /** Course Title */
            course_title: string;
            /** Kind */
            kind: string;
            /** Source Text */
            source_text: string;
            /** Status */
            status: string;
            /** Unparsed Text */
            unparsed_text: string;
            /** Parsed Rule */
            parsed_rule: string;
            /** Parsed English */
            parsed_english: string;
            /** Override Rule */
            override_rule: string | null;
            /** Override Note */
            override_note: string | null;
            /** Effective Rule */
            effective_rule: string;
            /** Effective English */
            effective_english: string;
            /** Reviewed */
            reviewed: boolean;
            /** Reviewed By */
            reviewed_by: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
            /** Source Changed */
            source_changed: boolean;
        };
        /** AttemptIn */
        AttemptIn: {
            /**
             * Code
             * @example CSC 231
             */
            code: string;
            status: components["schemas"]["AttemptStatus"];
            /** Term */
            term?: string | null;
            /** Grade */
            grade?: string | null;
            /** Units */
            units?: number | null;
        };
        /**
         * AttemptStatus
         * @enum {string}
         */
        AttemptStatus: "completed" | "in_progress" | "failed" | "withdrawn" | "incomplete" | "not_counted";
        /** AuditOut */
        AuditOut: {
            /** Id */
            id: number;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Actor */
            actor: string;
            /** Action */
            action: string;
            /** Target */
            target: string;
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
        };
        /** CatalogInfoOut */
        CatalogInfoOut: {
            /** Program Id */
            program_id: string;
            /** Program Name */
            program_name: string;
            /** Catalog Year */
            catalog_year: string | null;
            /** Source */
            source: string | null;
            /** Source Date */
            source_date: string | null;
            /** Revision */
            revision: number;
        };
        /**
         * ChangeAction
         * @enum {string}
         */
        ChangeAction: "drop" | "delay";
        /** ChangeIn */
        ChangeIn: {
            /**
             * Code
             * @example CSC 231
             */
            code: string;
            action: components["schemas"]["ChangeAction"];
        };
        /** CountedCourseOut */
        CountedCourseOut: {
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Units */
            units: number;
            /**
             * State
             * @enum {string}
             */
            state: "completed" | "in_progress" | "planned";
        };
        /** CourseListOut */
        CourseListOut: {
            /** Total */
            total: number;
            /** Courses */
            courses: components["schemas"]["CourseRef"][];
        };
        /** CourseOut */
        CourseOut: {
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Units */
            units: number;
            /** Description */
            description: string;
            /** Component */
            component: string | null;
            /** Notices */
            notices: string[];
            /**
             * Offered Terms
             * @description Seasons it runs in; null means every Fall and Spring
             */
            offered_terms: string[] | null;
            /** Rules */
            rules: components["schemas"]["RuleOut"][];
            /** Unlocks */
            unlocks: components["schemas"]["CourseRef"][];
            /** Groups */
            groups: {
                [key: string]: string;
            }[];
        };
        /** CourseRef */
        CourseRef: {
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Units */
            units: number;
        };
        /**
         * DegreeMapOut
         * @description Every course on the student's path by term, with prerequisite links (F5.1).
         */
        DegreeMapOut: {
            /** Columns */
            columns: components["schemas"]["MapColumnOut"][];
            /** Nodes */
            nodes: components["schemas"]["MapNodeOut"][];
            /** Edges */
            edges: components["schemas"]["MapEdgeOut"][];
        };
        /** EligibleOut */
        EligibleOut: {
            course: components["schemas"]["CourseRef"];
            /** Group Key */
            group_key: string;
            /** Group Label */
            group_label: string;
            /** Unlocks */
            unlocks: number;
            /** Advisories */
            advisories: string[];
            /** Take With */
            take_with: string[];
        };
        /** GatewayOut */
        GatewayOut: {
            course: components["schemas"]["CourseRef"];
            /** Dependents */
            dependents: number;
            /** Direct Dependents */
            direct_dependents: string[];
        };
        /**
         * GpaOut
         * @description Cumulative GPA, the last graded term's GPA and the retakes that would raise the CGPA most (F7).
         */
        GpaOut: {
            /** Cumulative */
            cumulative: number;
            /** Units */
            units: number;
            last_term: components["schemas"]["TermGpaOut"] | null;
            /** Retakes */
            retakes: components["schemas"]["RetakeOut"][];
            /** Assumptions */
            assumptions: string[];
        };
        /** GroupOut */
        GroupOut: {
            /** Key */
            key: string;
            /** Title */
            title: string;
            /** Label */
            label: string;
            /** Role */
            role: string;
            /** Units Required */
            units_required: number;
            /** Requires All */
            requires_all: boolean;
            /** Courses */
            courses: components["schemas"]["CourseRef"][];
            /** Children */
            children: components["schemas"]["GroupOut"][];
        };
        /** GroupProgressOut */
        GroupProgressOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Role */
            role: string;
            /** Units Required */
            units_required: number;
            /** Completed */
            completed: number;
            /** In Progress */
            in_progress: number;
            /** Planned */
            planned: number;
            /** Remaining */
            remaining: number;
            /** Courses */
            courses: components["schemas"]["CountedCourseOut"][];
            /** Children */
            children: components["schemas"]["GroupProgressOut"][];
        };
        /** GroupSuggestionsOut */
        GroupSuggestionsOut: {
            /** Group Key */
            group_key: string;
            /** Group Label */
            group_label: string;
            /** Units Needed */
            units_needed: number;
            /** Suggestions */
            suggestions: components["schemas"]["SuggestionOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** HistoryParseIn */
        HistoryParseIn: {
            /** Text */
            text: string;
        };
        /** HistoryParseOut */
        HistoryParseOut: {
            /** Rows */
            rows: components["schemas"]["HistoryRowOut"][];
            /** Unread */
            unread: components["schemas"]["UnreadLineOut"][];
            /** Ignored Line Count */
            ignored_line_count: number;
            /** Duplicates Removed */
            duplicates_removed: number;
        };
        /** HistoryRowOut */
        HistoryRowOut: {
            /** Code */
            code: string;
            /** Title */
            title: string | null;
            /** Term */
            term: string | null;
            /** Grade */
            grade: string | null;
            /** Units */
            units: number | null;
            status: components["schemas"]["AttemptStatus"] | null;
            /** Sis Status */
            sis_status: string | null;
            /** Line */
            line: number;
            /** Issues */
            issues: string[];
        };
        /** ImportRunOut */
        ImportRunOut: {
            /** Id */
            id: number;
            /** Program Id */
            program_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
            /** Published */
            published: boolean;
            /** Actor */
            actor: string;
            /** Report */
            report: {
                [key: string]: unknown;
            };
        };
        /** InsightsOut */
        InsightsOut: {
            /** Gateways */
            gateways: components["schemas"]["GatewayOut"][];
            /** Longest Chain */
            longest_chain: components["schemas"]["CourseRef"][];
        };
        /** IssueOut */
        IssueOut: {
            /**
             * Severity
             * @enum {string}
             */
            severity: "warning" | "info";
            /** Message */
            message: string;
            /** Code */
            code: string | null;
        };
        /** LeftItemOut */
        LeftItemOut: {
            /** Group Key */
            group_key: string;
            /** Group Label */
            group_label: string;
            /** Units Needed */
            units_needed: number;
            /** Required Courses */
            required_courses: components["schemas"]["CourseRef"][];
            /** Options */
            options: components["schemas"]["CourseRef"][];
            /** Open Pool */
            open_pool: boolean;
        };
        /** LockIn */
        LockIn: {
            /**
             * Code
             * @example CSC 231
             */
            code: string;
            /**
             * Term
             * @example Fall 2027
             * @example 2027/2028 Fall
             */
            term: string;
        };
        /** MapColumnOut */
        MapColumnOut: {
            /** Label */
            label: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "completed" | "current" | "planned" | "unscheduled";
        };
        /** MapEdgeOut */
        MapEdgeOut: {
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /** MapNodeOut */
        MapNodeOut: {
            /** Key */
            key: string;
            /** Code */
            code: string | null;
            /** Title */
            title: string;
            /** Units */
            units: number;
            /**
             * Status
             * @enum {string}
             */
            status: "done" | "in_progress" | "planned" | "choice" | "blocked";
            /** Column */
            column: number;
            /** Group Label */
            group_label: string | null;
        };
        /** MetaOut */
        MetaOut: {
            /** Version */
            version: string;
            /** Catalog Revision */
            catalog_revision: number;
            /** Interests */
            interests: components["schemas"]["OptionOut"][];
            /** Goals */
            goals: components["schemas"]["OptionOut"][];
            /** Workloads */
            workloads: string[];
            /** Paces */
            paces: string[];
            /** Standing Credits */
            standing_credits: {
                [key: string]: number;
            };
            /** Defaults */
            defaults: {
                [key: string]: unknown;
            };
            /** Assumptions */
            assumptions: string[];
            /** Disclaimer */
            disclaimer: string;
        };
        /**
         * MinorPlanOut
         * @description The minor the student chose: its requirements now and once the plan is done.
         *
         *     A course can count toward the major and the minor at the same time.
         */
        MinorPlanOut: {
            /** Program Id */
            program_id: string;
            /** Name */
            name: string;
            /** Total Units */
            total_units: number;
            /** Source */
            source: string | null;
            /** Source Date */
            source_date: string | null;
            progress: components["schemas"]["ProgressOut"];
            progress_with_plan: components["schemas"]["GroupProgressOut"];
        };
        /** OptionOut */
        OptionOut: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /**
         * Pace
         * @enum {string}
         */
        Pace: "on_time" | "fastest";
        /** PlanItemOut */
        PlanItemOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "course" | "slot";
            /** Key */
            key: string;
            /** Code */
            code: string | null;
            /** Title */
            title: string;
            /** Units */
            units: number;
            /** Reason */
            reason: string;
            /** Group Key */
            group_key: string | null;
            /** Group Label */
            group_label: string | null;
            /** Locked */
            locked: boolean;
            /** Unlocks */
            unlocks: number;
            /** Advisories */
            advisories: string[];
            /** Suggestions */
            suggestions: components["schemas"]["CourseRef"][];
            /**
             * Alternatives
             * @description Courses that could replace this one in the same term: same requirement, offered then, prerequisites done in earlier terms, corequisites in the same term
             */
            alternatives: components["schemas"]["CourseRef"][];
        };
        /** PlanOut */
        PlanOut: {
            start_term: components["schemas"]["TermOut"];
            graduation_term: components["schemas"]["TermOut"] | null;
            on_time_term: components["schemas"]["TermOut"] | null;
            /** Terms */
            terms: components["schemas"]["PlannedTermOut"][];
            /** Issues */
            issues: components["schemas"]["IssueOut"][];
            /** Unscheduled */
            unscheduled: components["schemas"]["PlanItemOut"][];
            /** Critical Chain */
            critical_chain: components["schemas"]["CourseRef"][];
            progress: components["schemas"]["ProgressOut"];
            progress_with_plan: components["schemas"]["GroupProgressOut"];
            /** Eligible Next Term */
            eligible_next_term: components["schemas"]["EligibleOut"][];
            degree_map: components["schemas"]["DegreeMapOut"];
            /** @description Null until the student has a graded course */
            gpa: components["schemas"]["GpaOut"] | null;
            /** @description Null when no minor was chosen */
            minor?: components["schemas"]["MinorPlanOut"] | null;
            catalog: components["schemas"]["CatalogInfoOut"];
            /** Assumptions */
            assumptions: string[];
            /** Disclaimer */
            disclaimer: string;
        };
        /** PlannedTermOut */
        PlannedTermOut: {
            term: components["schemas"]["TermOut"];
            /** Units */
            units: number;
            /** Items */
            items: components["schemas"]["PlanItemOut"][];
        };
        /** PreferencesIn */
        PreferencesIn: {
            /**
             * Preferred Units
             * @default 15
             */
            preferred_units: number;
            /**
             * Max Units
             * @default 18
             */
            max_units: number;
            /** @default on_time */
            pace: components["schemas"]["Pace"];
            /**
             * Include Summer
             * @default false
             */
            include_summer: boolean;
            /**
             * Summer Max Units
             * @default 6
             */
            summer_max_units: number;
            /** Start Term */
            start_term?: string | null;
            /** Locks */
            locks?: components["schemas"]["LockIn"][];
            /** Exclude */
            exclude?: string[];
            /** Include */
            include?: string[];
            /** Interests */
            interests?: string[];
            /** Goal */
            goal?: string | null;
            /** @default balanced */
            workload: components["schemas"]["Workload"];
        };
        /** ProgramDetailOut */
        ProgramDetailOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Catalog Year */
            catalog_year: string | null;
            /** Total Units */
            total_units: number;
            /** Source */
            source: string | null;
            /** Source Date */
            source_date: string | null;
            root: components["schemas"]["GroupOut"];
        };
        /** ProgramSummaryOut */
        ProgramSummaryOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Catalog Year */
            catalog_year: string | null;
            /** Total Units */
            total_units: number;
            /** Source */
            source: string | null;
            /** Source Date */
            source_date: string | null;
        };
        /** ProgressOut */
        ProgressOut: {
            /** Percent Complete */
            percent_complete: number;
            /** Completed Units */
            completed_units: number;
            /** In Progress Units */
            in_progress_units: number;
            root: components["schemas"]["GroupProgressOut"];
            /** Not Counted */
            not_counted: components["schemas"]["CourseRef"][];
            /** Whats Left */
            whats_left: components["schemas"]["LeftItemOut"][];
        };
        /** ReadyOut */
        ReadyOut: {
            /**
             * Status
             * @constant
             */
            status: "ready";
            /**
             * Database
             * @constant
             */
            database: "ok";
            /** Catalog Revision */
            catalog_revision: number;
            /** Programs */
            programs: number;
            /**
             * Today
             * Format: date
             */
            today: string;
        };
        /** RecommendationsOut */
        RecommendationsOut: {
            /** Groups */
            groups: components["schemas"]["GroupSuggestionsOut"][];
        };
        /** RetakeOut */
        RetakeOut: {
            course: components["schemas"]["CourseRef"];
            /** Grade */
            grade: string;
            /**
             * With A
             * @description CGPA if the retake earns an A
             */
            with_a: number;
            /**
             * With B
             * @description CGPA if the retake earns a B
             */
            with_b: number;
            /**
             * In Plan
             * @description Already in the plan (a failed course that must be retaken anyway)
             */
            in_plan: boolean;
        };
        /** RuleCheckIn */
        RuleCheckIn: {
            /** Rule */
            rule: string;
        };
        /** RuleCheckOut */
        RuleCheckOut: {
            /** Valid */
            valid: boolean;
            /** Rule */
            rule?: string | null;
            /** English */
            english?: string | null;
            /** Error */
            error?: string | null;
            /** Position */
            position?: number | null;
            /** Unknown Courses */
            unknown_courses?: string[];
        };
        /** RuleOut */
        RuleOut: {
            /** Kind */
            kind: string;
            /** English */
            english: string;
            /** Rule */
            rule: string;
            /** Source Text */
            source_text: string;
            /** Status */
            status: string;
            /** Reviewed */
            reviewed: boolean;
            /** Overridden */
            overridden: boolean;
        };
        /** RuleUpdateIn */
        RuleUpdateIn: {
            /**
             * Rule
             * @description Rule in the admin rule language, or NONE
             */
            rule: string;
            /** Note */
            note?: string | null;
        };
        /** ShiftOut */
        ShiftOut: {
            /** Code */
            code: string;
            /** Title */
            title: string;
            before: components["schemas"]["TermOut"] | null;
            after: components["schemas"]["TermOut"] | null;
        };
        /**
         * StudentIn
         * @description Everything the planner needs. Nothing here is stored (F11.5).
         */
        StudentIn: {
            /** Program Id */
            program_id: string;
            /** Minor Id */
            minor_id?: string | null;
            /** Attempts */
            attempts?: components["schemas"]["AttemptIn"][];
            preferences?: components["schemas"]["PreferencesIn"];
        };
        /** SuggestionOut */
        SuggestionOut: {
            course: components["schemas"]["CourseRef"];
            /** Score */
            score: number;
            /** Reasons */
            reasons: string[];
            /** Eligible Now */
            eligible_now: boolean;
            /** Missing */
            missing: string[];
        };
        /** TermGpaOut */
        TermGpaOut: {
            term: components["schemas"]["TermOut"];
            /** Gpa */
            gpa: number;
            /** Units */
            units: number;
        };
        /** TermOut */
        TermOut: {
            /** Label */
            label: string;
            /** Year */
            year: number;
            /**
             * Season
             * @enum {string}
             */
            season: "Spring" | "Summer" | "Fall";
        };
        /** UnreadLineOut */
        UnreadLineOut: {
            /** Line */
            line: number;
            /** Text */
            text: string;
            /** Reason */
            reason: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WhatIfIn */
        WhatIfIn: {
            /** Program Id */
            program_id: string;
            /** Minor Id */
            minor_id?: string | null;
            /** Attempts */
            attempts?: components["schemas"]["AttemptIn"][];
            preferences?: components["schemas"]["PreferencesIn"];
            change: components["schemas"]["ChangeIn"];
        };
        /** WhatIfOut */
        WhatIfOut: {
            change: components["schemas"]["ChangeIn"];
            /** Terms Later */
            terms_later: number;
            before_graduation: components["schemas"]["TermOut"] | null;
            after_graduation: components["schemas"]["TermOut"] | null;
            /** Shifts */
            shifts: components["schemas"]["ShiftOut"][];
            plan: components["schemas"]["PlanOut"];
        };
        /**
         * Workload
         * @enum {string}
         */
        Workload: "light" | "balanced" | "challenging";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    ready_api_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaOut"];
                };
            };
        };
    };
    programs_api_v1_programs_get: {
        parameters: {
            query?: {
                kind?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    program_detail_api_v1_programs__program_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    insights_api_v1_programs__program_id__insights_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    courses_api_v1_courses_get: {
        parameters: {
            query?: {
                q?: string | null;
                subject?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_detail_api_v1_courses__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_history_api_v1_history_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoryParseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryParseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    progress_api_v1_planner_progress_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_api_v1_planner_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_what_if_api_v1_planner_what_if_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhatIfIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatIfOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommendations_api_v1_planner_recommendations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_v1_admin_rules_get: {
        parameters: {
            query?: {
                show?: "all" | "needs_review" | "partial" | "unparsed" | "overridden" | "source_changed" | "reviewed";
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRuleListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_rule_api_v1_admin_rules_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleCheckIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleCheckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_rule_api_v1_admin_rules__rule_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_rule_api_v1_admin_rules__rule_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_override_api_v1_admin_rules__rule_id__override_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    imports_api_v1_admin_imports_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_api_v1_admin_audit_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
