"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-08

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("target", sa.String(length=200), nullable=False),
        sa.Column(
            "detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_at"), ["at"], unique=False)

    op.create_table(
        "catalog_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "courses",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("units", sa.Float(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("component", sa.String(length=60), nullable=True),
        sa.Column(
            "notices",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("source_program", sa.String(length=64), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "import_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("program_id", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column(
            "report",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("import_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_import_runs_program_id"), ["program_id"], unique=False)

    op.create_table(
        "programs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("sis_title", sa.String(length=300), nullable=True),
        sa.Column("catalog_year", sa.String(length=20), nullable=True),
        sa.Column("total_units", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=300), nullable=True),
        sa.Column("source_date", sa.Date(), nullable=True),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "requirement_groups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("program_id", sa.String(length=64), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("units_required", sa.Float(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["requirement_groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["program_id"], ["programs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("program_id", "key", name="uq_group_program_key"),
    )
    with op.batch_alter_table("requirement_groups", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_requirement_groups_program_id"), ["program_id"], unique=False)

    op.create_table(
        "requisite_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("course_code", sa.String(length=16), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column(
            "parsed_expr",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("parse_status", sa.String(length=16), nullable=False),
        sa.Column("unparsed_text", sa.Text(), nullable=False),
        sa.Column(
            "override_expr",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("override_is_none", sa.Boolean(), nullable=False),
        sa.Column("override_note", sa.Text(), nullable=True),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.Column("reviewed_by", sa.String(length=120), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_changed", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["course_code"], ["courses.code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_code", "kind", name="uq_rule_course_kind"),
    )
    with op.batch_alter_table("requisite_rules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_requisite_rules_course_code"), ["course_code"], unique=False)
        batch_op.create_index(batch_op.f("ix_requisite_rules_parse_status"), ["parse_status"], unique=False)
        batch_op.create_index(batch_op.f("ix_requisite_rules_reviewed"), ["reviewed"], unique=False)

    op.create_table(
        "group_courses",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("course_code", sa.String(length=16), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["course_code"], ["courses.code"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["group_id"], ["requirement_groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("group_id", "course_code"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group_courses")
    with op.batch_alter_table("requisite_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_requisite_rules_reviewed"))
        batch_op.drop_index(batch_op.f("ix_requisite_rules_parse_status"))
        batch_op.drop_index(batch_op.f("ix_requisite_rules_course_code"))

    op.drop_table("requisite_rules")
    with op.batch_alter_table("requirement_groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_requirement_groups_program_id"))

    op.drop_table("requirement_groups")
    op.drop_table("programs")
    with op.batch_alter_table("import_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_import_runs_program_id"))

    op.drop_table("import_runs")
    op.drop_table("courses")
    op.drop_table("catalog_state")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_at"))

    op.drop_table("audit_log")
    # ### end Alembic commands ###
